//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.Histories = new HashSet<Histories>();
            this.TransferHistories = new HashSet<TransferHistories>();
            this.TransferHistories1 = new HashSet<TransferHistories>();
        }
    
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string CardNumber { get; set; }
        public string CardReqMount { get; set; }
        public string CardReqYear { get; set; }
        public string Cvv { get; set; }
        public int ActorId { get; set; }
        public int CurrencyTypeId { get; set; }
        public int AccountTypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Lookups Lookups { get; set; }
        public virtual Lookups Lookups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Histories> Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferHistories> TransferHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferHistories> TransferHistories1 { get; set; }
    }
}
